const actions = {
  FETCH_JOBS_SUCCESS: 'FETCH_JOBS_SUCCESS',
  FETCH_JOBS_FAIL: 'FETCH_JOBS_FAIL',
  FETCH_JOB_SUCCESS: 'FETCH_JOB_SUCCESS',
  FETCH_JOB_FAIL: 'FETCH_JOB_FAIL',
  FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
  FETCH_EVENTS_FAIL: 'FETCH_EVENTS_FAIL'
};

export default actions;
